# Generated by Django 5.0.6 on 2024-06-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
