# Generated by Django 5.0.6 on 2024-06-06 06:11

import django.db.models.deletion
import django.utils.timezone
import roomApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Hotel1',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID del hotel')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigoHotel', models.CharField(max_length=20, verbose_name='Código de Hotel')),
                ('precio', models.PositiveIntegerField(default=450000, verbose_name='Precio')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Inauguración')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('foto', models.ImageField(default='hoteles/hotel.png', null=True, upload_to=roomApp.models.Hotel1.generar_nombre_archivo)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomApp.categoria', verbose_name='Categoría')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomApp.departamento', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'hotel',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
