# Generated by Django 5.0.6 on 2024-06-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0003_categoria1_remove_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='departamento',
        ),
    ]
