# Generated by Django 5.0.6 on 2024-06-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0004_remove_hotel_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel1',
            name='fechaNac',
        ),
    ]
