# Generated by Django 4.2.13 on 2024-06-29 04:12

from django.db import migrations, models
import django.utils.timezone
import roomApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0005_remove_hotel1_fechanac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cargo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID del trabajador')),
                ('nombre', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='hotel1',
            name='descripcion',
            field=models.CharField(default=1, max_length=255, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='categorias/categorias.png', null=True, upload_to=roomApp.models.Categoria.generar_nombre_categoria),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel1',
            name='codigoHotel',
            field=models.PositiveIntegerField(default=450000, verbose_name='codigoHotel'),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
