# Generated by Django 4.2.13 on 2024-06-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0006_cargo_quienessomos_trabajador_delete_categoria1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
